export const tagOptions = [
    { key: 'photography', text: 'Photography', value: 'Photography' },
    { key: 'landscape', text: 'Landscape', value: 'Landscape' },
    { key: 'nature', text: 'Nature', value: 'Nature' },
    { key: 'concert', text: 'Concert', value: 'Concert' },
    { key: 'roadtrip', text: 'Roadtrip', value: 'Roadtrip' },
    { key: 'city', text: 'City', value: 'City' },
    { key: 'abstract', text: 'Abstract', value: 'Abstract' },
    { key: 'fashion', text: 'Fashion', value: 'Fashion' },
    { key: 'boudoir', text: 'Boudoir', value: 'Boudoir' },
    { key: 'portraits', text: 'Portraits', value: 'Portraits' },
    { key: 'mountains', text: 'Mountains', value: 'Mountains' },
    { key: 'beach', text: 'Beach', value: 'Beach' },
    { key: 'travel', text: 'Travel', value: 'Travel' },
    { key: 'vacation', text: 'Vacation', value: 'Vacation' },
    { key: 'urban', text: 'Urban', value: 'Urban' },
    { key: 'macro', text: 'Macro', value: 'Macro' },
    { key: 'product', text: 'Product', value: 'Product' },
    { key: 'sports', text: 'Sports', value: 'Sports' },
    { key: 'lifestyle', text: 'Lifestyle', value: 'Lifestyle' },
    { key: 'smartphone', text: 'Smartphone', value: 'Smartphone' },
    { key: 'sony', text: 'Sony', value: 'Sony' },
    { key: 'nikon', text: 'Nikon', value: 'Nikon' },
    { key: 'cannon', text: 'Cannon', value: 'Cannon' },
    { key: 'dslr', text: 'DSLR', value: 'DSLR' },
    { key: 'mirrorless', text: 'Mirrorless', value: 'Mirrorless' },
    { key: 'flash', text: 'Flash', value: 'Flash' },
]